### PR TITLE
Finish

### PR DESCRIPTION
**Pull request by CakeCrusher**

### CODE REVIEW

**Review by mluukkai — APPROVED** [review]
good job!

**Review by mluukkai — APPROVED** [review]
good job!

**Review by mluukkai — APPROVED** [review]
wtf

**Review by mluukkai — APPROVED** [review]
what is going on?

**Comment by CakeCrusher** [comment]
@mluukkai I have no idea, I am assuming you did not meant to comment "good job!" twice? Or maybe the check did not respond as you intended? 

One (probably unrelated) thing that was happening throughout the course was that immediately after making the pull request it would show green like this..
image
and then after a couple of seconds it would go yellow and start running the workflow checks.

**Pull request merged**
